### ISSUE TITLE
Running on GKE

### ISSUE THREAD

**Issue by AlexsJones** [iJanki/kubecron#1]
```
panic: No Auth Provider found for name "gcp"

goroutine 1 [running]:
github.com/iJanki/kubecron/cmd.mustGetClientset(0x4)
	/home/jonesax/Go/src/github.com/iJanki/kubecron/cmd/root.go:53 +0xe5
github.com/iJanki/kubecron/cmd.run(0x177cb60, 0xc42022fc10, 0x1, 0x1)
	/home/jonesax/Go/src/github.com/iJanki/kubecron/cmd/run.go:26 +0x4a
github.com/spf13/cobra.(*Command).execute(0x177cb60, 0xc42022fbc0, 0x1, 0x1, 0x177cb60, 0xc42022fbc0)
	/home/jonesax/Go/src/github.com/spf13/cobra/command.go:757 +0x2c1
github.com/spf13/cobra.(*Command).ExecuteC(0x177c900, 0xc420078058, 0x0, 0x10c30e0)
	/home/jonesax/Go/src/github.com/spf13/cobra/command.go:843 +0x334
github.com/spf13/cobra.(*Command).Execute(0x177c900, 0x0, 0x0)
	/home/jonesax/Go/src/github.com/spf13/cobra/command.go:791 +0x2b
github.com/iJanki/kubecron/cmd.Execute()
	/home/jonesax/Go/src/github.com/iJanki/kubecron/cmd/root.go:28 +0x2d
main.main()
	/home/jonesax/Go/src/github.com/iJanki/kubecron/main.go:9 +0x20

```

I ran this on a cluster with `kubecron run jobname` and saw this, any ideas?

**Comment by danielec7** [comment]
Yes I have a fix for that. I will push in a bit.

**Comment by danielec7** [comment]
Can you try now recompiling from source please? 

```go get -u github.com/iJanki/kubecron```

I will release binaries later if it works for you.

**Comment by AlexsJones** [comment]
Ace, works thank you :pray:
